name: Test

on: 
  workflow_run: 
    workflows: 
      - Create Prerelease
      - Create Release
    types: [requested]
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - develop
 
permissions:
  contents: read 

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set_branch.outputs.branch_name }}
    steps:
      - name: Determine target branch
        id: set_branch
        run: echo "branch_name=${BRANCH}" >> "$GITHUB_OUTPUT"
        env:
          BRANCH: >-
            ${{ github.event_name == 'pull_request'
                && github.event.pull_request.base.ref
                || 'main' }}
                
  test-main:
    needs: discover
    if: ${{ needs.discover.outputs.branch_name == 'main'  }}
    uses: Stillpoint-Software/shared-workflows/.github/workflows/test.yml@main
    with:
      solution_name: ${{ vars.SOLUTION_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  test-develop:
    needs: discover
    if: ${{ needs.discover.outputs.branch_name == 'develop' }}
    uses: Stillpoint-Software/shared-workflows/.github/workflows/test.yml@develop
    with:
      solution_name: ${{ vars.SOLUTION_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
