name: Test

on: 
  workflow_run: 
    workflows: 
      - Create Prerelease
      - Create Release
    types: [requested]
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - develop
 
permissions:
  contents: read 

jobs:
  test:
    uses: Stillpoint-Software/shared-workflows/.github/workflows/test.yml@main
    with:
      solution_name: ${{ vars.SOLUTION_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}