name: Test

on:
  workflow_run:
    workflows: [Create Prerelease, Create Release]
    types: [requested]
    branches: [main, develop]        
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, develop]

permissions:
  contents: read
  actions: read

jobs:
  discover:
    name: Which brand to run for every trigger type
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set_branch.outputs.branch_name }}
    steps:
      - id: set_branch
        run: echo "branch_name=${BRANCH}" >> "$GITHUB_OUTPUT"
        env:
          BRANCH: >-
            ${{ github.event_name == 'workflow_run'
                && github.event.workflow_run.head_branch      # ① workflow_run
                || github.event_name == 'pull_request'
                && github.event.pull_request.base.ref         # PRs
                || github.ref_name }}                         # push / dispatch

  test-main:
    needs: discover
    if: ${{ needs.discover.outputs.branch_name == 'main' }}
    uses: Stillpoint-Software/shared-workflows/.github/workflows/test.yml@main
    with:
      solution_name: ${{ vars.SOLUTION_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-develop:
    needs: discover
    if: ${{ needs.discover.outputs.branch_name == 'develop' }}
    uses: Stillpoint-Software/shared-workflows/.github/workflows/test.yml@develop
    with:
      solution_name: ${{ vars.SOLUTION_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
